export interface TimeProperty {
  id: string;
  label: string;
},

export const TIMEPROPERTIES: TimeProperty[] = [
  { label: "Date of baptism", id: "37 " },
  { label: "Date of death", id: "38 " },
  { label: "Beginning of composition", id: "39 " },
  { label: "Date of burial", id: "40 " },
  { label: "Terminus post quem", id: "41 " },
  { label: "Terminus ante quem", id: "43 " },
  { label: "Date of receipt", id: "44 " },
  { label: "Start time of reported events", id: "45 " },
  { label: "End of events reported", id: "46 " },
  { label: "Begin date", id: "49 " },
  { label: "End date", id: "50 " },
  { label: "Date of birth", id: "77 " },
  { label: "Date as stated", id: "96 " },
  { label: "Date", id: "106 " },
  { label: "Date of confirmation", id: "182 " },
  { label: "Date of last will", id: "214 " },
  { label: "Date of publication", id: "222 " },
  { label: "Gregorian calendar start date", id: "289 " },
  { label: "First known date", id: "290 " },
  { label: "Last known date", id: "291 " },
  { label: "<Last confirmed date>", id: "303 " },
  { label: "Date of consecration/ ordination", id: "321 " },
  { label: "Date of disputation", id: "P392 " },
  { label: "Date of ennoblement", id: "P394 " },
  { label: "Date of creation", id: "P412 " },
  { label: "Date of finding", id: "P432 " },
  { label: "Date of retirement", id: "P459 " },
  { label: "Date of artifact", id: "P536 " },
  { label: "Date of premiere", id: "P551 " },
  { label: "Last modified", id: "P612 " },
  { label: "Commemorative date", id: "P779 " },
  { label: "Renewal date", id: "P818 " },
  { label: "Minimum date (property constraint)", id: "P1041 " },
  { label: "Maximum date (property constraint)", id: "P1042 " },
  { label: "Circumcision Date (religious)", id: "P1060 " },
  { label: "Banns of marriage, date", id: "P1079 " },
  { label: "Date of verdict", id: "P1104 " },
  { label: "End date (terminus ante quem)", id: "P1123 " },
  { label: "Begin date (terminus ante quem)", id: "P1124 " },
  { label: "End date (terminus post quem)", id: "P1125 " },
  { label: "Begin date (terminus post quem)", id: "P1126 " },
  { label: "Date of first publication", id: "P1152 " },
];
